project:
  type: book
  output-dir: _book

engine: knitr

book:
  title: "ggplot2 extended"
  reader-mode: true
  
  page-footer:
    left: |
      ggplot2 extended was written by Antti Rask.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a> and is hosted on <a href="https://www.netlify.com">Netlify</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://https://ggplot2-extended-book.com/
  repo-url: https://github.com/AnttiRask/ggplot2-extended-book/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - preface.qmd

    - part: getting_started.qmd
      chapters:
        - ggplot2.qmd
        - installing_packages.qmd

    - part: layers.qmd
      chapters:
        - data.qmd
        - geoms.qmd
        - stats.qmd
        - annotations.qmd
        - scales_and_guides.qmd
        - coords.qmd
        - facets.qmd
        - themes.qmd

    - part: special_cases.qmd
      chapters:
        - maps.qmd
        - networks.qmd
        - interactive_plots.qmd
        - animation.qmd

    - part: shortcuts.qmd
      chapters:
        - helpers.qmd
        - interactive_tools.qmd

    - part: getting_ready_to_publish.qmd
      chapters:
        - finishing_touches.qmd
        - arranging_plots.qmd

    - part: beyond_r.qmd
      chapters:
        - bi_tools.qmd
        - large_language_models.qmd
        - python.qmd
        
    - part: case_studies.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - g2e.scss
    code-link: true
  
    author-meta: "Antti Rask"
    include-in-header: "goatcounter.html"
    callout-appearance: simple

editor: visual