# Stats {#sec-stats}

```{r}
#| echo: false
#| message: false
#| results: asis
source("warning.R")
```

## Combining data visualization and statistical modeling {#sec-combining-data-visualization-and-statistical-modeling}

## Convex hull {#sec-convex-hull}

## Inferential statistical tests {#sec-inferential-statistical-tests}

### F-test {#sec-f-test}

### Pearson's Chi-squared test {#sec-pearsons-chi-squared-test}

### Test for association between paired samples {#sec-test-for-association-between-paired-samples}

### Test of equal or given proportions {#sec-test-of-equal-or-given-proportions}

### T-test {#sec-t-test}

## Interaction plot {#sec-interaction-plot}

### CGPfunctions {#sec-CGPfunctions}

## Linear regression {#sec-linear-regression}

### Diagnostic plots {#sec-diagnostic-plots}

### Regression line equation and R-squared {#sec-regression-line-equation-and-r-squared}

## Lorenz Curve {#sec-lorenz-curve}

## Markov chain Monte Carlo {#sec-markov-chain-monte-carlo}

## Multi-stat binning layer {#sec-multi-stat-binning-layer}

## Overlay normal density plot {#sec-overlay-normal-density-plot}

## P-values {#sec-p-values}

## P-P plot {#sec-p-p-plot}

## Q-Q plot {#sec-q-q-plot}

## Quality control chart {#sec-quality-control-chart}

## Proportions according to custom denominator {#sec-proportions-according-to-custom-denominator}

### ggstats {#sec-ggstats}

## Random forests {#sec-random-forests}

## ROC curves {#sec-roc-curves}

## Sample data and distribution vectors {#sec-sample-data-and-distribution-vectors}

## Seasonal adjustment {#sec-seasonal-adjustment}

## Statistics for reporting the results of model fits {#sec-statistics-for-reporting-the-results-of-model-fits}

## Survival analysis {#sec-survival-analysis}

## Tornado plot {#sec-tornado-plot}
